### ISSUE TITLE
[BUG] (erro no comando de help)

### ISSUE THREAD

**Issue by anajuliadiscord** [Crypton-Technologies/Crypton#37]
**Describe the bug**
O bot nao responde o comando.

![Capture+_2021-04-28-05-13-57](https://user-images.githubusercontent.com/72071948/116370542-e3b90b00-a7e0-11eb-9b20-d54db8e7feb5.png)

**Comment by MEGATANK58** [comment]
This is because of a missing if statement, gonna patch it thanks

**Comment by anajuliadiscord** [comment]
okay
