### ISSUE TITLE
[BUG] (Erro no comando help(categoria)

### ISSUE THREAD

**Issue by anajuliadiscord** [Crypton-Technologies/Crypton#39]
**Describe the bug**
O bot Nao responde help(categoria)

.

**Screenshots**
![Capture+_2021-04-28-05-53-30](https://user-images.githubusercontent.com/72071948/116376323-832ccc80-a7e6-11eb-94e8-42c025f52a57.png)

**Comment by MEGATANK58** [comment]
I think the last pr merge has caused a few unintentional bugs
