### ISSUE TITLE
[BUG] (is giving an error in the code, look at the print.)

### ISSUE THREAD

**Issue by anajuliadiscord** [Crypton-Technologies/Crypton#41]
![Capture+_2021-04-30-06-14-01](https://user-images.githubusercontent.com/72071948/116674889-9329e500-a97b-11eb-9c1f-b31514fe9260.png)

**Comment by MEGATANK58** [comment]
#40 Fixes this

**Comment by MEGATANK58** [comment]
This issue has been fixed with the merge of the latest pr
